[package]
name = "roguelike"
version = "0.1.0"
authors = ["David <david.abraham.1337@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hecs = "0.3.2"
resources = "1.1.0"
rltk = { version = "0.8.0" }
